// yorn data g end jishig bolgoj hadgalaad baigaa
export const BayruudList = [
  {
    id: "10",
    img: "/Halloween.svg",
    title: "Halloween",
    subtitle: "Аймшиг дагуулсан шөнө",
    negTitle: "Сөрөг тал",
    negText: "Хүүхдүүд айж магадгүй",
    bannerColor: "#6B21A8",
    products: [
      { id: "p1", name: "Аймшгийн маск", price: 8000, img: "/products/mask.svg" },
      { id: "p2", name: "Чимэглэл гэрэл", price: 12000, img: "/products/lights.svg" },
      { id: "p3", name: "Хулуу чимэглэл", price: 9500, img: "/products/pumpkin.svg" },
    ],
  },
  {
    id: "11",
    img: "/Huuhdiin.svg",
    title: "Хүүхдийн баяр",
    subtitle: "Хүүхдийн инээмсэглэл",
    negTitle: "Сөрөг тал",
    negText: "Эцэг эхчүүд бэлгийн дарамттай",
    bannerColor: "#F59E0B",
    products: [
      { id: "p4", name: "Тоглоомын машин", price: 15000, img: "/products/car.svg" },
      { id: "p5", name: "Барби хүүхэлдэй", price: 18000, img: "/products/doll.svg" },
      { id: "p6", name: "Зурах багц", price: 10000, img: "/products/artkit.svg" },
    ],
  },
  {
    id: "12",
    img: "/Lunar.svg",
    title: "Цагаан сар",
    subtitle: "Өв уламжлал, хүндэтгэл",
    negTitle: "Сөрөг тал",
    negText: "Зардал их",
    bannerColor: "#059669",
    products: [
      { id: "p7", name: "Загасны таваг", price: 25000, img: "/products/fish_plate.svg" },
      { id: "p8", name: "Бэлэгний багц", price: 30000, img: "/products/gift_set.svg" },
      { id: "p9", name: "Дээл", price: 60000, img: "/products/deel.svg" },
    ],
  },
  {
    id: "13",
    img: "/Mart.svg",
    title: "Мартын 8",
    subtitle: "Эмэгтэйчүүдэд зориулав",
    negTitle: "Сөрөг тал",
    negText: "Цэцэг үнэ өснө",
    bannerColor: "#EC4899",
    products: [
      { id: "p10", name: "Цэцгийн баглаа", price: 20000, img: "/products/flowers.svg" },
      { id: "p11", name: "Гоо сайхны сет", price: 35000, img: "/products/cosmetics.svg" },
      { id: "p12", name: "Үнэртэй ус", price: 45000, img: "/products/perfume.svg" },
    ],
  },
  {
    id: "14",
    img: "/Naadam.svg",
    title: "Наадам",
    subtitle: "Үндэсний их баяр",
    negTitle: "Сөрөг тал",
    negText: "Тээврийн түгжрэл",
    bannerColor: "#10B981",
    products: [
      { id: "p13", name: "Хурууд", price: 8000, img: "/products/huruud.svg" },
      { id: "p14", name: "Наадмын туг", price: 12000, img: "/products/flag.svg" },
      { id: "p15", name: "Ардын хувцас", price: 70000, img: "/products/naadam_clothes.svg" },
    ],
  },
  {
    id: "15",
    img: "/NewYear.svg",
    title: "Шинэ жил",
    subtitle: "Шинэ оны баяр",
    negTitle: "Сөрөг тал",
    negText: "Зарлага ихэсдэг",
    bannerColor: "#1D4ED8",
    products: [
      { id: "p16", name: "Шинэ жилийн мод", price: 40000, img: "/products/tree.svg" },
      { id: "p17", name: "Гэрийн чимэглэл", price: 10000, img: "/products/decoration.svg" },
      { id: "p18", name: "Цасан өвгөний хувцас", price: 30000, img: "/products/santa_suit.svg" },
    ],
  },
  {
    id: "16",
    img: "/soldier_day.svg",
    title: "Цэргийн баяр",
    subtitle: "Эрчүүдийн баяр",
    negTitle: "Сөрөг тал",
    negText: "Заримд нь хамааралгүй",
    bannerColor: "#374151",
    products: [
      { id: "p19", name: "Армийн цаг", price: 25000, img: "/products/army_watch.svg" },
      { id: "p20", name: "Гар буу тоглоом", price: 18000, img: "/products/toy_gun.svg" },
      { id: "p21", name: "Цэргийн малгай", price: 15000, img: "/products/army_hat.svg" },
    ],
  },
  {
    id: "17",
    img: "/valentine.svg",
    title: "Валентин",
    subtitle: "Хосуудын баяр",
    negTitle: "Сөрөг тал",
    negText: "Ганц бие хүмүүст хэцүү",
    bannerColor: "#DC2626",
    products: [
      { id: "p22", name: "Зүрхэн шоколад", price: 9000, img: "/products/heart_choco.svg" },
      { id: "p23", name: "Хайрын захиа", price: 5000, img: "/products/love_letter.svg" },
      { id: "p24", name: "Хос цамц", price: 35000, img: "/products/couple_shirts.svg" },
    ],
  },
  {
    id: "18",
    img: "/christmas.svg",
    title: "Зул сар",
    subtitle: "Христийн баяр",
    negTitle: "Сөрөг тал",
    negText: "Монголд түгээмэл биш",
    bannerColor: "#2563EB",
    products: [
      { id: "p25", name: "Зул сарын од", price: 6000, img: "/products/star.svg" },
      { id: "p26", name: "Бэлгийн хайрцаг", price: 15000, img: "/products/gift_box.svg" },
      { id: "p27", name: "Цасан бөмбөлөг", price: 12000, img: "/products/snow_globe.svg" },
    ],
  },
];
